app/workfinder/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get "registrations/new"
  get "registrations/create"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show"

  get "/signup", to: "registrations#new", as: "signup"
  post "/signup", to: "registrations#create"

  get "/messages/", to: "messages#index"
  get "/messages/:id", to: "messages#show", as: :message
  post "/messages", to: "messages#create"

  get "/appointments/", to: "appointments#index"
  post "/appointments/", to: "appointments#create"

  get "/reviews/:id", to: "reviews#show"
  post "/reviews", to: "reviews#create"

  resources :appointments do
    member do
      patch :schedule
      patch :cancel
    end
  end
  root "users#index"
  resources :users
  resources :messages
  resources :reviews
end

app/workfinder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/workfinder/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :worker, class_name: "User", optional: true
  belongs_to :customer, class_name: "User", optional: true
end

app/workfinder/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :project_id, class_name: "Project"
  belongs_to :bidder_id, class_name: "User"
end

app/workfinder/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/workfinder/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/workfinder/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :owner, class_name: "User"
end

app/workfinder/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewee, class_name: "User"
end

app/workfinder/app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/workfinder/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :owned_projects, class_name: "Project", foreign_key: "owner_id"
end

app/workfinder/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @message = Message.new
    @sender = current_user
    if params[:id].present?
      @receiver = User.find(params[:id])
      @messages = Message.where("(sender_id = ? and receiver_id = ?) or (sender_id = ? and receiver_id = ?)", @sender.id, params[:id], params[:id], @sender.id).order(:created_at)
    else
      @messages = []
    end
  end
  def index
    @current_user = current_user
    @users = User.where(
      id: Message.select(:receiver_id).where("(sender_id = ?)", @current_user.id)
    ).or(
      User.where(
        id: Message.select(:sender_id).where("(receiver_id = ?)", @current_user.id)
      )
    )
  end
  def create
    @message = Message.new(message_params)
    @message.save
  end

  def message_params
    params.require(:message).permit(:body, :sender_id, :receiver_id)
  end
end

app/workfinder/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.new
    @reviewer = current_user
    if params[:id].present?
      @reviewee = User.find(params[:id])
      @reviews = Review.includes(:reviewee).where("reviewee_id = ?", params[:id])
    else
      @reviews = []
    end
  end
  def create
    @review = Review.new(review_params)
    @review.save
  end

  def review_params
    params.require(:review).permit(:body, :reviewer_id, :reviewee_id, :rating)
  end
end

app/workfinder/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_path, alert: "Try again later." }
  layout false, only: [ :new ]
  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, status: :see_other
  end
end

app/workfinder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    if params[:city].present?
      @users = @users.where("city LIKE ?", "%" + params[:city] + "%")
    end
    if params[:state].present?
      @users = @users.where("state LIKE ?", "%" + params[:state] + "%")
    end
  end

  def show
    @visitor = current_user
    @user = User.find(params[:id])
    @appointments = Appointment.where(worker_id: @user.id, customer_id: nil)
  end
end

app/workfinder/app/helpers/application_helper.rb
module ApplicationHelper
end

app/workfinder/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/workfinder/app/helpers/messages_helper.rb
module MessagesHelper
end

app/workfinder/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/workfinder/app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/workfinder/app/helpers/servicemen_helper.rb
module ServicemenHelper
end

app/workfinder/app/helpers/users_helper.rb
module UsersHelper
end

app/workfinder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Workfinder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Workfinder">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      .nav {
        list-style: none;       /* remove bullets */
        padding: 0;             /* remove default padding */
        margin: 0;              /* remove default margin */
        display: flex;          /* horizontal layout */
        gap: 20px;              /* space between items */
      }
    </style>
    <%= yield :head %>
    

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul class="nav">
        <% if authenticated? %>
          <li><%= link_to "Home", root_path, class: "nav-item" %></li>
          <li><%= link_to "My Appointments", appointments_path, class: "nav-item" %></li>
          <li><%= link_to "Messages", messages_path, class: "nav-item" %></li>
          <li><%= button_to "Log out", session_path, method: :delete, class: "logout-button nav-item" %></li>
        <% else %>
          <li><%= link_to "Home", root_path, class: "nav-item" %></li>
        <% end %>
      </ul>
    </nav>

    <main>
      <%= yield %>
    </main>
  </body>
</html>