app/workfinder/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get "registrations/new"
  get "registrations/create"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show"

  get "/signup", to: "registrations#new", as: "signup"
  post "/signup", to: "registrations#create"

  get "/messages/", to: "messages#index"
  get "/messages/:id", to: "messages#show", as: :message
  post "/messages", to: "messages#create"

  get "/appointments/", to: "appointments#index"
  post "/appointments/", to: "appointments#create"

  get "/reviews/:id", to: "reviews#show"
  post "/reviews", to: "reviews#create"

  resources :appointments do
    member do
      patch :schedule
      patch :cancel
    end
  end
  root "users#index"
  resources :users
  resources :messages
  resources :reviews
end

app/workfinder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/workfinder/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :worker, class_name: "User", optional: true
  belongs_to :customer, class_name: "User", optional: true
end

app/workfinder/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :project_id, class_name: "Project"
  belongs_to :bidder_id, class_name: "User"
end

app/workfinder/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/workfinder/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/workfinder/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :owner, class_name: "User"
end

app/workfinder/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewee, class_name: "User"
end

app/workfinder/app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/workfinder/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :owned_projects, class_name: "Project", foreign_key: "owner_id"
end

app/workfinder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/workfinder/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointment = Appointment.new
    @current_user=current_user
    @users = User.all
    if current_user.role == 1
      @scheduled_appointments = Appointment.where(worker_id: current_user.id).where.not(customer_id: nil)
      @appointment_slots = Appointment.where(worker_id: current_user.id).where(customer_id: nil)
    else
      @scheduled_appointments = Appointment.where(customer_id: current_user.id)
    end
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.save
  end

  def appointment_params
    params.require(:appointment).permit(:worker_id, :start_time, :end_time, :customer_id)
  end

  def schedule
    appointment_id=params[:id]
    user_id=current_user.id
    Appointment.find(appointment_id).update(customer_id: user_id)
  end
  def cancel
    appointment_id=params[:id]
    Appointment.find(appointment_id).update(customer_id: nil)
  end
end

app/workfinder/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @message = Message.new
    @sender = current_user
    if params[:id].present?
      @receiver = User.find(params[:id])
      @messages = Message.where("(sender_id = ? and receiver_id = ?) or (sender_id = ? and receiver_id = ?)", @sender.id, params[:id], params[:id], @sender.id).order(:created_at)
    else
      @messages = []
    end
  end
  def index
    @current_user = current_user
    @users = User.where(
      id: Message.select(:receiver_id).where("(sender_id = ?)", @current_user.id)
    ).or(
      User.where(
        id: Message.select(:sender_id).where("(receiver_id = ?)", @current_user.id)
      )
    )
  end
  def create
    @message = Message.new(message_params)
    @message.save
  end

  def message_params
    params.require(:message).permit(:body, :sender_id, :receiver_id)
  end
end

app/workfinder/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_password_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.find_by(email: params[:email])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      @user.sessions.destroy_all
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/workfinder/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.new
    @reviewer = current_user
    if params[:id].present?
      @reviewee = User.find(params[:id])
      @reviews = Review.includes(:reviewee).where("reviewee_id = ?", params[:id])
    else
      @reviews = []
    end
  end
  def create
    @review = Review.new(review_params)
    @review.save
  end

  def review_params
    params.require(:review).permit(:body, :reviewer_id, :reviewee_id, :rating)
  end
end

app/workfinder/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_path, alert: "Try again later." }
  layout false, only: [ :new ]
  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, status: :see_other
  end
end

app/workfinder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    if params[:city].present?
      @users = @users.where("city LIKE ?", "%" + params[:city] + "%")
    end
    if params[:state].present?
      @users = @users.where("state LIKE ?", "%" + params[:state] + "%")
    end
  end

  def show
    @visitor = current_user
    @user = User.find(params[:id])
    @appointments = Appointment.where(worker_id: @user.id, customer_id: nil)
  end
end

app/workfinder/app/helpers/application_helper.rb
module ApplicationHelper
end

app/workfinder/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/workfinder/app/helpers/messages_helper.rb
module MessagesHelper
end

app/workfinder/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/workfinder/app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/workfinder/app/helpers/servicemen_helper.rb
module ServicemenHelper
end

app/workfinder/app/helpers/users_helper.rb
module UsersHelper
end

app/workfinder/app/views/appointments/index.html.erb
<% if @current_user.role == 1 %>
  <div class="appointments-page">
  <h1>Your appointments and time slots</h1>

  <h2>Create a new time slot</h2>

  <div class="timeslot-form-wrapper">
    <%= form_with model: @appointment do |form| %>
      <%= form.label :start_time, "Start time" %>
      <%= form.datetime_local_field :start_time %>

      <%= form.label :end_time, "End time" %>
      <%= form.datetime_local_field :end_time %>

      <%= form.hidden_field :worker_id, value: @current_user.id %>

      <%= form.submit "Submit" %>
    <% end %>
  </div>
</div>
  <h2>Your open slots</h2>
  <table border="1">
    <thead>
      <tr>
        <td>Start time</td>
        <td>End time</td>
      </tr>
    </thead>
    <tbody>
      <% @appointment_slots.each do |appointment_slot| %>
        <tr>
          <td>
            <%= appointment_slot.start_time %>
          </td>
          <td>
            <%= appointment_slot.end_time %>
          </td>
        </tr>
      <% end %>

      <tr>
      </tr>
    </tbody>
  </table>
  <h2> Scheduled appointments</h2>
  <table border="1">
    <thead>
      <tr>
        <td>Start time</td>
        <td>End time</td>
        <td>Customer</td>
        <td>Cancel</td>
      </tr>
    </thead>
    <tbody>
      <% @scheduled_appointments.each do |appointment| %>
        <tr>
          <td>
            <%= appointment.start_time %>
          </td>
          <td>
            <%= appointment.end_time %>
          </td>
          <% 
            customer=@users.find(appointment.customer_id)
          %>
          <td>
            <%= link_to user_path(customer) do %>
              <%= customer.username %>
            <% end %>
          </td>
          <td> <%= button_to "Cancel", cancel_appointment_path(appointment), method: :patch %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1> Your appointments</h1>
  <table border="1">
    <thead>
      <tr>
        <td>Start time</td>
        <td>End time</td>
        <td>Associate</td>
        <td>Cancel</td>
      </tr>
    </thead>
    <tbody>
      <% @scheduled_appointments.each do |appointment| %>
        <tr>
          <td>
            <%= appointment.start_time %>
          </td>
          <td>
            <%= appointment.end_time %>
          </td>
          <% 
            worker=@users.find(appointment.worker_id)
          %>
          <td>
            <%= link_to user_path(worker) do %>
              <%= worker.username %>
            <% end %>
          </td>
          <td> <%= button_to "Cancel", cancel_appointment_path(appointment), method: :patch %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/workfinder/app/views/messages/index.html.erb
<h1>Messages</h1>

<div id="messages" class="messages-container">
  <% @users.each do |user| %>
    <%= link_to message_path(user), style: "text-decoration: none; color: inherit;" do %>
      <div class= "user-card">
        <p><span class="label"><strong>Username:</strong> <%= user.username %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/workfinder/app/views/messages/show.html.erb
<h1>Messages with <%= @receiver.username %></h1>

<div class="message-thread-page">
  <div class="message-form-container">
    <h2>Write a message</h2>
    <%= form_with model: @message, class: "message-form" do |form| %>
      <div class="form-group">
        <%= form.text_field :body, placeholder: "Type your message..." %>
        <%= form.hidden_field :sender_id, value: @sender.id %>
        <%= form.hidden_field :receiver_id, value: @receiver.id %>
      </div>
      <div class="form-group">
        <%= form.submit "Send" %>
      </div>
    <% end %>
  </div>

  <div class="message-table-container">
    <table border="1">
      <thead>
        <tr>
          <th>Sender</th>
          <th>Message body</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% @messages.all.each do |message| %>
          <tr>
            <td> 
              <% if message.sender_id == @sender.id %>
                <%= @sender.username %>
              <% else %>
                <%= @receiver.username %>
              <% end %> 
            </td>
            <td> <%= message.body %> </td>
            <td> <%= message.created_at %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/workfinder/app/views/users/index.html.erb
<h1 class="h1">Servicemen</h1>

<h2 class="h2">Search By Location</h2>

<%= form_with url: users_path, method: :get, local: true, html: { class: "search-form" } do |f| %>
  <div class = "search-form-inner">
    <div class="form-group">
      <%= f.label :city, "City" %>
      <%= f.text_field :city, placeholder: "Search by city" %>
    </div>
    <div class="form-group">
      <%= f.label :state, "State" %>
      <%= f.text_field :state, placeholder: "Search by state" %>
    </div>
    <%= f.submit "Search", class: "search-button" %>
  </div>
<% end %>

<div id="users">
  <% @users.where(role: 1).each do |user| %>
    <%= link_to user_path(user), style: "text-decoration: none; color: inherit;" do %>
      <div class="user-card">
        <div>
          <h2><%= user.name %></h2>
          <p><strong>State:</strong> <%= user.state %></p>
          <p><strong>Description:</strong> <%= user.description %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/workfinder/app/views/users/show.html.erb
<div class="users-page">
  <h2><%= @user.name %></h2>
  <div>
  <div class="user-card">
    <p><span class="label">Username:</span> <%= @user.username %></p>
    <p><span class="label">Email:</span> <%= @user.email %></p>
    <p><span class="label">City:</span> <%= @user.city %></p>
    <p><span class="label">State:</span> <%= @user.state %></p>
  </div>
    <p><strong>Description:</strong> <%= @user.description %></p>
  </div>
  <button type="button" onclick="window.location='<%= message_path(@user) %>'">Message</button>
  <button type="button" onclick="window.location='<%= review_path(@user) %>'">Reviews</button>

  <% if @user.role == 1 %>
    <div class="appointment-card">    
      <strong>Available appointment time slots</strong>
      <table border="1">
        <thead>
          <tr>
            <th>Start time</th>
            <th>End time</th>
            <% if @visitor.role != 1 %>
              <th>Schedule</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @appointments.all.each do |appointment| %>
          <tr>
            <td> <%= appointment.start_time %> </td>
            <td> <%= appointment.end_time %> </td>
            <% if @visitor.role != 1 %>
              <td> <%= button_to "Schedule", schedule_appointment_path(appointment), method: :patch %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>